### ISSUE TITLE
Custom class and style

### ISSUE THREAD

**Issue by mariofornaroli** [vnseattle/newsfeed9x#1]
Hi, I like very much the idea! I’d like to contribute adding the possibility for the user to add custom classes and styles. Are you ok if I code it and submit a pull request?

**Comment by vnseattle** [comment]
Hi Mario, 
Thank you for your interest in the project. You are welcome to contribute it.  
PS: We are building a team to build this project. Do you want to join to the team?

**Comment by mariofornaroli** [comment]
Hi! Yes, I would like to join the team. Count me in 👍 . I’ve just opened a pull request where I generalized the list item structure, added custom class names and styles. Let me know what you think about it

**Comment by vnseattle** [comment]
Updated
